### ISSUE TITLE
Solution about "failed to load ktx texture /home/xxx/cgf/assets/misc/ktx/day.ktx"

### ISSUE THREAD

**Issue by CodingCatMountain** [jianglongye/cgf#2]
As mentioned in Readme, the simulation environment is sapien. And the author adopted the similar environment setting up `.py` file from [dex-hand-teleop](https://github.com/yzqin/dex-hand-teleop/issues/4). So the solution to this problem can refer to [this link](https://github.com/yzqin/dex-hand-teleop/issues/4). @jianglongye Since cgf and dex-hand-teleop are different projects, I highly suggest you to add the related commands in README.

**Comment by jianglongye** [comment]
thanks for your suggestion, we add this in our README
